# Numpy
  python module or library
# Types are :- 1:np.array 2:np.array with dtype 3:np.arange(with reshape) 4:np.random 5:np.ones 6:np.zeros 7:np.linspace 8:np.identity

# Methods are :- 1.min 2.max 3.sum 4.prod 5.sort 6.concatenate 7.where

# Array Attributes
# Types are :- 1.ndim 2.shape 3.size 4.itemsize 5.dtype
    
# Indexing and Slicing

# Array Operations
# Types are :- 1.reshape 2.scalaroperations 3.relational 4.vectoroperations

# Methods are :- 1._split 2.broadcast 

In [32]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(type(a))
b = np.array([[1,2],[3,4]])
print(b)
c = np.array([[[1,2,3],[4,5,6]]])
print(c)

d = np.array([1,2,3,4],dtype='str')
print(d)

e = np.arange(1,11)
print(e)
f = np.arange(10,0,-1)
print(f)

g = np.arange(1,13).reshape(4,3)
print(g)
h = np.arange(1,15).reshape(7,2)
print(h)                                  #not possible it will give ValueError

i = np.random.random((3,4))
print(i)
j = np.random.randint((2,10))
print(j)

k = np.ones((3,4))
print(k)
l = np.zeros((4,3))
print(l)

m = np.identity(3)
print(m)

n = np.linspace(-100,100,10,dtype="int")
print(n)

[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
[[[1 2 3]
  [4 5 6]]]
['1' '2' '3' '4']
[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]
[[0.19742657 0.38645796 0.07932209 0.58196875]
 [0.48759077 0.3540787  0.85448644 0.04016596]
 [0.47686152 0.08416265 0.88451498 0.64819133]]
[0 4]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[-100  -78  -56  -34  -12   11   33   55   77  100]


In [25]:
import numpy as np
a = np.arange(1,13)
b = np.arange(1,13).reshape(4,3)
c = np.arange(1,13).reshape(2,2,3)
print(a)
print()
print(b)
print()
print(c)
print()
print(a.ndim,a.size,a.itemsize,a.dtype)
print(a.shape)
print()
print(b.ndim,b.size,b.itemsize,b.dtype)
print(b.shape)
print()
print(c.ndim,c.size,c.itemsize,c.dtype)
print(c.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

1 12 4 int32
(12,)

2 12 4 int32
(4, 3)

3 12 4 int32
(2, 2, 3)


In [47]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a[4])
print(a[-8])
print(a[3:9])
print(a[::-1])
#fancy indexing
print(a[a%2==0])
print(a[(a%2==0)&(a>5)])
print(a[[2,7,9]])
print()

b = np.arange(1,13).reshape(3,4)
print(b[1,2])
print(b[-2,-2])
print(b[::-1,::-1])
print(b[::2,::3])
print(b[::2,::4])
print(b[::2,[0,2,3]])
print()

c = np.arange(1,13).reshape(2,2,3)
print(c[1,0,0])
print(c[-1,-2,-3])
print(c[::-1,::-1,::-1])
print(c[:,0,:])

5
5
[4 5 6 7 8 9]
[12 11 10  9  8  7  6  5  4  3  2  1]
[ 2  4  6  8 10 12]
[ 6  8 10 12]
[ 3  8 10]

7
7
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 1  4]
 [ 9 12]]
[[1]
 [9]]
[[ 1  3  4]
 [ 9 11 12]]

7
7
[[[12 11 10]
  [ 9  8  7]]

 [[ 6  5  4]
  [ 3  2  1]]]
[[1 2 3]
 [7 8 9]]


In [53]:
#Scalar Opeartion
a = np.arange(1,13).reshape(3,4)
print(a)
print()
print(a+2)
print()
print(a-2)
print()
print(a*2)
print()
print(a/2)
print()
print(a//2)
print()
print(a%2)
print()
print(a**2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]

[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]]

[[0 1 1 2]
 [2 3 3 4]
 [4 5 5 6]]

[[1 0 1 0]
 [1 0 1 0]
 [1 0 1 0]]

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [55]:
#Vector Operation(Arithmetic)
b = np.arange(1,13).reshape(3,4)
print(a)
print(b)
print()
print(a+b)
print()
print(a-b)
print()
print(a*b)
print()
print(a/b)
print()
print(a//b)
print()
print(a%b)
print()
print(a**b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[         1          4         27        256]
 [      3125      46656     823543   16777216]
 [ 387420489 1410065408 1843829075 -251658240]]


In [75]:
b = np.arange(13,25).reshape(4,3)
c = np.dot(a,b)  #3x4 and 4x3
print(c)

[[1030 1088 1146]
 [1310 1384 1458]
 [1590 1680 1770]]


In [76]:
#Relational
print(a==15)
print(a>5)
#print(a>b)
#print(a<b)

[[False False  True False]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [85]:
#Methods
x = np.random.randint(1,100,size=(3,4))
print(x)
print(np.min(x))
print(np.min(x,axis=0))
print(np.min(x,axis=1))
print(np.min(x,axis=1).reshape(-1,3))   #if both (-1,-1) then ValueError otherwise 1stx2nd
print()

print(np.max(x))
print(np.max(x,axis=0))
print(np.max(x,axis=1))
print()

print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

[[68 74 91 73]
 [38 81 82 59]
 [27 73 44 73]]
27
[27 73 44 59]
[68 38 27]
[[68 38 27]]

91
[68 81 91 73]
[91 82 73]

783
[133 228 217 205]
[306 260 217]


In [83]:
s=0
for i in x:
    for j in i:
        s += j
print(s)

421


In [92]:
print(np.sort(x))
print(np.sort(x,axis=0))
print(np.sort(x,axis=1))
print()

print(np.argsort(x[:,-1]))              #give index

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]

[0 3 1 4 2 5]


In [93]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(1,10).reshape(3,3)
x = np.concatenate((a,b),axis=0)
y = np.concatenate((a,b),axis=1)
print(a)
print(b)
print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


In [6]:
import numpy as np
a = np.random.randint(1,100,size=(3,4))    
print(np.where(a>50))                        #give index
print(np.where(a>50,1,0))                    #binary array
print(np.where(a>70,1,np.where(a>50,2,0)))

(array([0, 0, 1, 1, 1, 2, 2], dtype=int64), array([0, 2, 1, 2, 3, 1, 3], dtype=int64))
[[1 0 1 0]
 [0 1 1 1]
 [0 1 0 1]]
[[1 0 1 0]
 [0 2 1 1]
 [0 2 0 1]]


In [8]:
from numpy import array, array_split
first_array = array([1, 2, 3, 4, 5, 6, 7, 8, 9])
my_array = array_split(first_array, 3)
print(my_array)
print()

first_array = array([1, 2, 3, 4, 5, 6, 7, 8, 9])
my_array = array_split(first_array, 5)
print(my_array)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9])]
