In [50]:
from abc import ABC,abstractmethod
import numpy as np


class Data(ABC):
    array = np.array([[64,13,100,46,69,85],[54,43,7,34,17,19],[73,73,90,77,53,14],[74,41,41,83,74,95],[48,31,74,49,67,99]])
    @abstractmethod
    def abcmethod(self):
        pass
    
class Match(Data):
    def abcmethod(self):
        print("Child method")
        
    def match_highscore(self,match_number):
        a = Data.array
        print("Highest score of match : ",np.max(a[match_number]))
        
    def player_lowscore(self,player_number):
        a = Data.array
        print("lowest score of player : ",np.min(a[:,player_number-1]))
                    
    def match_total(self):
        a = Data.array
        s = Data.array.sum(axis=1)
        s = s.reshape(-1,1)
        b = np.concatenate((a,s),axis=1)
        print("Match total score : \n",b)
        
    def sorted_matchtotal_hightolow(self):
        y = list(b)
        y.sort(key = lambda x : x[-1])
        y = np.array(y)
        print("Sorted : \n",y)
    
    def player_totalscore(self):
        a = Data.array
        print("Total score of player : ",np.sum(a,axis=0))
        
    def binary_array(self):
        a = Data.array
        ba = np.where(a>50,1,2)
        print("Binary Array : \n",ba)
    
    
obj = Match()
print(obj.array)
print()
obj.abcmethod()
obj.match_highscore(0)
obj.player_lowscore(0)
obj.match_total()
obj.sorted_matchtotal_hightolow()
obj.player_totalscore()
obj.binary_array()

[[ 64  13 100  46  69  85]
 [ 54  43   7  34  17  19]
 [ 73  73  90  77  53  14]
 [ 74  41  41  83  74  95]
 [ 48  31  74  49  67  99]]

Child method
Highest score of match :  100
lowest score of player :  14
Match total score : 
 [[ 64  13 100  46  69  85 377]
 [ 54  43   7  34  17  19 174]
 [ 73  73  90  77  53  14 380]
 [ 74  41  41  83  74  95 408]
 [ 48  31  74  49  67  99 368]]
Sorted : 
 [[1 2]
 [3 4]]
Total score of player :  [313 201 312 289 280 312]
Binary Array : 
 [[1 2 1 2 1 1]
 [1 2 2 2 2 2]
 [1 1 1 1 1 2]
 [1 2 2 1 1 1]
 [2 2 1 2 1 1]]
