In [2]:
from abc import ABC,abstractmethod
import numpy as np


class Data(ABC):
    array = np.array([[64,13,100,46,69,85],[54,43,7,34,17,19],[73,73,90,77,53,14],[74,41,41,83,74,95],[48,31,74,49,67,99]])
    @abstractmethod
    def abcmethod(self):
        pass
    
class Match(Data):
    def abcmethod(self):
        print("Child method")
        
    def match_highscore(self,match_number):
        a = Data.array
        print("Highest score of match : ",np.max(a[match_number]))
        
    def player_lowscore(self,player_number):
        a = Data.array
        print("lowest score of player : ",np.min(a[:,player_number-1]))
                    
    def match_total(self):
        a = Data.array
        s = Data.array.sum(axis=1)
        s = s.reshape(-1,1)
        b = np.concatenate((a,s),axis=1)
        print("Match total score : \n",b)
        
    def sorted_matchtotal_hightolow(self):
        a = Data.array
        s = Data.array.sum(axis=1)
        s = s.reshape(-1,1)
        b = np.concatenate((a,s),axis=1)
        y = list(b)
        y.sort(key = lambda x : x[-1])
        y = np.array(y)
        print("Sorted : \n",y)
    
    def player_totalscore(self):
        a = Data.array
        print("Total score of player : ",np.sum(a,axis=0))
        
    def binary_array(self):
        a = Data.array
        ba = np.where(a>50,1,2)
        print("Binary Array : \n",ba)
    
    
obj = Match()
print(obj.array)
print()
obj.abcmethod()
obj.match_highscore(0)
obj.player_lowscore(0)
obj.match_total()
obj.sorted_matchtotal_hightolow()
obj.player_totalscore()
obj.binary_array()

[[ 64  13 100  46  69  85]
 [ 54  43   7  34  17  19]
 [ 73  73  90  77  53  14]
 [ 74  41  41  83  74  95]
 [ 48  31  74  49  67  99]]

Child method
Highest score of match :  100
lowest score of player :  14
Match total score : 
 [[ 64  13 100  46  69  85 377]
 [ 54  43   7  34  17  19 174]
 [ 73  73  90  77  53  14 380]
 [ 74  41  41  83  74  95 408]
 [ 48  31  74  49  67  99 368]]
Sorted : 
 [[ 54  43   7  34  17  19 174]
 [ 48  31  74  49  67  99 368]
 [ 64  13 100  46  69  85 377]
 [ 73  73  90  77  53  14 380]
 [ 74  41  41  83  74  95 408]]
Total score of player :  [313 201 312 289 280 312]
Binary Array : 
 [[1 2 1 2 1 1]
 [1 2 2 2 2 2]
 [1 1 1 1 1 2]
 [1 2 2 1 1 1]
 [2 2 1 2 1 1]]


In [13]:
import numpy as np
m1=np.array([15,9,12,6,7])
m2=np.array([25,10,16,12,8])
m3=np.array([12,3,17,13,11])
m4=np.array([7,11,18,14,9])

d1=np.array([15,25,12,7])
d2=np.array([9,10,3,11])
d3=np.array([12,16,17,18])
d4=np.array([6,12,13,14])
d5=np.array([7,8,11,9])

print("Minimum production of day5 : ",np.min(d5))
print("Maximum production of m1 : ",np.max(m1[0]))
print("Total Production of ")
print("m1:",np.sum(m1,axis=0)," ","m2:",np.sum(m2,axis=0)," ","m3:",np.sum(m3,axis=0)," ","m4:",np.sum(m4,axis=0))
print("Total Production of ")
print("d1:",np.sum(d1,axis=0)," ","d2: ",np.sum(d2,axis=0)," ","d3:",np.sum(d3,axis=0)," ","d4:",np.sum(d4,axis=0)," ","d5:",np.sum(d5,axis=0)," ")

Minimum production of day5 :  7
Maximum production of m1 :  15
Total Production of 
m1: 49   m2: 71   m3: 56   m4: 59
Total Production of 
d1: 59   d2:  33   d3: 63   d4: 45   d5: 35  
